import Head from "next/head";
import Image from "next/image";
import { Option } from "../src/components/Option";
import { Dropdown } from "../src/components/Dropdown";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div
          style={{
            backgroundColor: "rgb(25,25,25)",
            padding: "10px 0px",
            width: "300px",
          }}
        >
          <Dropdown
            status="Active"
            text="Select..."
            options={[
              { color: "Green", text: "Hello" },
              { color: "Gray", text: "Hola" },
              { color: "Orange", text: "Bonjour" },
            ]}
          ></Dropdown>
        </div>
      </main>
    </div>
  );
}
